# name: Run tests, pre-commit stuff and type checking for parselmouth

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

        - uses: prefix-dev/setup-pixi@v0.9.0
          with:
            pixi-version: "latest"
            manifest-path: pyproject.toml

        - name: Run tests
          run: |
           pixi run test

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          environments: >-
            fmt
            type-checking

      - name: pre-commit
        run: pixi run pre-commit-run --color=always --show-diff-on-failure --all

      - name: type check
        run: pixi run type-check
